version: "3"

services:
  database:
    container_name: database
    image: 'bitnami/postgresql:latest'
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=bycoders
    volumes:
      - 'postgresql_data:/app/postgresql'

  api:
    container_name: api
    build: ./bycoders-api
    command:
      - java -jar api.jar
    ports:
      - "8080:8080"
    volumes:
      - ./bycoders-api/target/bycoders-0.0.1-SNAPSHOT.jar:/bycoders/api/api.jar

  web:
    container_name: web
    build: ./bycoders-web
    command:
      - npm start
    ports:
      - "3000:3000"
    volumes:
      - ./bycoders-web:/bycoders/web

volumes:
  postgresql_data:
    driver: local
